# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymodel',
            options={'permissions': (('view_not_released', 'Can see my models that are not released.'),)},
        ),
        migrations.AddField(
            model_name='mymodel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
